### ISSUE TITLE
后续考虑加入esLint和jest吗？

### ISSUE THREAD

**Issue by 1998feng** [mf950511/react-admin#9]
RT

**Comment by mf950511** [comment]
最近两天会接入eslint，jest暂时没有接入的准备，后续可以完善接入

**Comment by 1998feng** [comment]
> 最近两天会接收eslint，jest暂时没有接收的准备，后续可以完善接收

期待学习。最近使用ts重构react hooks 项目，eslint一直有些问题

**Comment by mf950511** [comment]
已支持
